title: RP Strength Documentation
description: Documentation for RP Strength Apps
remote_theme: just-the-docs/just-the-docs

url: https://docs.rpstrength.com

aux_links:
  RP Diet Coach App Home: https://rpstrength.com/pages/diet-coach-app

aux_links_new_tab: true

logo: "/assets/images/logo-docs-big@2x.png"

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark

callouts:
  note:
    title: Note
    color: purple

defaults:
  -
    scope:
      path: "docs/**/index.md"
    values:
      layout: "default"
      permalink: "/:path/"
  -
    scope:
      path: "docs"
    values:
      layout: "default"
      permalink: "/:path/:basename/"
