title: RP Strength Documentation
description: Documentation for Renaissance Periodization Products
remote_theme: just-the-docs/just-the-docs

url: https://rp-docs.integratedfitnesscoaching.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "https://rpstrength.com/cdn/shop/files/logomark_1.svg?crop=center&height=32&v=1708462121&width=32"


collections:
  docs:
    permalink: "/:path/"
    output: true

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark

callouts:
  note:
    title: Note
    color: purple

## just_the_docs:
##  collections:
##    docs:
##      name: RP Documentation TEST

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

